### ISSUE TITLE
Error in Linux example of README

### ISSUE THREAD

**Issue by CozyFlower** [secana/dotnet-interactive-docker#14]
Thanks for making this. There is a small error in the example command for Linux

```
# doesn't work properly on linux
docker run -it --rm -p 8888:8888 -v $pwd:/home/user/local secana/dotnet-interactive:latest
```

The key here is `$pwd` which inserts the value of the `pwd` environment variable. Instead we want to substitute the output from executing the `pwd` command; which we do by wrapping it in parentheses: `$(pwd)` - regular parentheses, not the curly brackets that powershell uses.

So the linux example command becomes

```
docker run -it --rm -p 8888:8888 -v $(pwd):/home/user/local secana/dotnet-interactive:latest
```

**Comment by secana** [comment]
Thanks for reporting! It's fixed.
