### ISSUE TITLE
Invalid mount

### ISSUE THREAD

**Issue by chrisamow** [secana/dotnet-interactive-docker#2]
Hi, thanks for this handy way to get up and running!

Using your instructions for linux on an ubuntu 20.04 LTS system got me:
```
docker: Error response from daemon: OCI runtime create failed: invalid mount {Destination::/home/user/local Type:bind Source:/var/lib/docker/volumes/2fe5275ab7003d85b3f00aa92f4bb09234623ebd2d30f7df1fda36df0b52403b/_data Options:[rbind]}: mount destination :/home/user/local not absolute: unknown.
```

I'll investigate further but thought you might want to know since it's once of the most important parts of your readme.

**Comment by secana** [comment]
Hi @chrisamow. I updated the Dockefile and uploaded a new Docker image with the latest version of Jupyter and .NET Interactive. I'm not sure about the unknown location, as everything works fine with the updated image. If you find out what the problem is, let me know.
